err_handler: Don't clobber dberrstr with oserrstr
The error handler was tending to use the oserrstr and not the dberrstr,
resulting in error messages like this:

    pymssql.OperationalError: (20009, 'Net-Lib error during Connection
    refused')

With this change, the dberrstr is also included resulting in:

    pymssql.OperationalError: (20009, 'DB-Lib error message 20009,
    severity 9:\nUnable to connect: Adaptive Server is unavailable or
    does not exist\nNet-Lib error during Connection refused\n')